### ISSUE TITLE
Mac OS X: bundle identifier is still com.github.atom

### ISSUE THREAD

**Issue by waywardmonkeys** [atom-archive/electron-starter#15]
On Mac OS X, the 2 plist files still list the `CFBundleIdentifier` as `com.github.com`:

```
  <key>CFBundleIdentifier</key>
  <string>com.github.atom</string>
```

This shows up in a crash dialog (which I got on exit).

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom-archive/electron-starter), this package is no longer maintained and is deprecated. We recommend that people use [electron-prebuilt](https://github.com/mafintosh/electron-prebuilt) and [electron-packager](https://github.com/maxogden/electron-packager) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
