### ISSUE TITLE
No parameter for settings directory

### ISSUE THREAD

**Issue by waywardmonkeys** [atom-archive/electron-starter#17]
There's no setting for the equivalent of `~/.atom`.

It would be nice if this were more OS-integrated than just a single field, since the location of this directory should differ between Mac OS X, Linux and Windows.

This is currently used (and hard-coded) in `src/coffee-cache.coffee`:

``` coffee
cacheDir = path.join(fs.absolute('~/.atom'), 'compile-cache')
```

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom-archive/electron-starter), this package is no longer maintained and is deprecated. We recommend that people use [electron-prebuilt](https://github.com/mafintosh/electron-prebuilt) and [electron-packager](https://github.com/maxogden/electron-packager) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
