### ISSUE TITLE
bootstrap script on Windows assumes existence of <user>\AppData\Roaming\npm directory

### ISSUE THREAD

**Issue by jflam** [atom-archive/electron-starter#48]
On a fresh install of node, the bootstrap script will fail with this error:

» .\script\bootstrap
Node: v0.10.33
npm: v1.4.28
Python: v2.7.9
Installing build modules...
Error: ENOENT, stat 'C:\Users\John\AppData\Roaming\npm'

Creating the npm directory allows it to proceed.

**Comment by paulcbetts** [comment]
This is an npm bug in the latest build :(

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom-archive/electron-starter), this package is no longer maintained and is deprecated. We recommend that people use [electron-prebuilt](https://github.com/mafintosh/electron-prebuilt) and [electron-packager](https://github.com/maxogden/electron-packager) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
