### ISSUE TITLE
Crash when requesting Jasmine to raise exceptions during tests

### ISSUE THREAD

**Issue by mmurdoch** [atom-archive/electron-starter#65]
Running the (default `hello-spec.coffee`) Jasmine test via 'View | Developer | Run Tests...' succeeds. However, if you then click the 'raise exceptions' checkbox you get a 'white screen of death' and the debugger breaks on line 38 of `index.js` producing the following message in the terminal window.

```
[21361:0329/111727:INFO:CONSOLE(38)] "SyntaxError: Unexpected token &
    at Object.parse (native)
    at window.onload (file:///[path removed]/atom-shell-starter/static/index.js:9:29)", 
        source: file:///[path removed]/atom-shell-starter/static/index.js (38)
```

The error seems to be thrown from this line in `index.js`:

```
var loadSettings = JSON.parse(decodeURIComponent(location.search.substr(14)));
```

**Comment by mmurdoch** [comment]
The error seems to be caused by the settings JSON having `&catch=false` appended to the end by Jasmine as it refreshes the content:

    {"bootstrapScript":"/[path removed]/atom-shell-starter/...}&catch=false

Which then means the `JSON.parse` call fails.

Whilst we *could* just strip this off as we do for the `?loadSettings=` prefix I suspect this would then not pass the 'raise exception' setting back to Jasmine...

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom-archive/electron-starter), this package is no longer maintained and is deprecated. We recommend that people use [electron-prebuilt](https://github.com/mafintosh/electron-prebuilt) and [electron-packager](https://github.com/maxogden/electron-packager) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
