### ISSUE TITLE
Time consuming build required before running tests

### ISSUE THREAD

**Issue by mmurdoch** [atom-archive/electron-starter#67]
Whenever I add or update a test (`xxxx-spec.coffee`) in the `spec` directory I have to run a build (`script/build`) otherwise the changes are not picked up when I run the tests.

This wouldn't be a huge problem except the build takes a long time (several minutes) to run.

Running a build seems to required regardless of whether I run the tests from the running app (via View | Developer | Run Tests...) or from the command line (using `script/grunt test`).

**Comment by hongrich** [comment]
This branch loads spec from resource path, so you don't have to do a complete rebuild every time you make changes to your tests. https://github.com/atom/atom-shell-starter/compare/master...hongrich:specs-from-resource-path

**Comment by mmurdoch** [comment]
@hongrich I've tested out your branch and it appears to work perfectly. It's made a huge improvement to my development speed. Thank you!

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom-archive/electron-starter), this package is no longer maintained and is deprecated. We recommend that people use [electron-prebuilt](https://github.com/mafintosh/electron-prebuilt) and [electron-packager](https://github.com/maxogden/electron-packager) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
