### ISSUE TITLE
Build step still needed?

### ISSUE THREAD

**Issue by kakaol** [atom-archive/electron-starter#71]
Hi, first, thanks for this great starter repo, it's very useful and helped me a lot. My small application is near the finish line and I've started with packaging for MacOSX. A Windows version will come later. And here I'm struggling a bit. 

In `electron-starter` you use `grunt-build-atom-shell` to download and compile the  `electron` source code. I've read about the reason ([Renaming atom.exe breaks native modules](https://github.com/atom/electron/issues/713) issue) for that. Then I started to take a deeper look into the atom packaging process and surprise, they just download the `electron` build and modify it. If I'm not wrong, also for windows. Can you confirm that?

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom-archive/electron-starter), this package is no longer maintained and is deprecated. We recommend that people use [electron-prebuilt](https://github.com/mafintosh/electron-prebuilt) and [electron-packager](https://github.com/maxogden/electron-packager) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
