### ISSUE TITLE
npm WARN cannot run in wd eightoheight@0.0.1 node -e 'process.exit(0)' (wd=/Users/adrian/Downloads/electron-starter-master)

### ISSUE THREAD

**Issue by adyz** [atom-archive/electron-starter#76]
When I do sudo npm install I get

npm WARN cannot run in wd eightoheight@0.0.1 node -e 'process.exit(0)' (wd=/Users/adrian/Downloads/electron-starter-master)

what's this?

ps. I'm a newbie

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom-archive/electron-starter), this package is no longer maintained and is deprecated. We recommend that people use [electron-prebuilt](https://github.com/mafintosh/electron-prebuilt) and [electron-packager](https://github.com/maxogden/electron-packager) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
