### ISSUE TITLE
Electron Rebuilding

### ISSUE THREAD

**Issue by ChrisMcKenzie** [atom-archive/electron-starter#77]
Perhaps i am doing something wrong but it seems that because the `build-atom-shell` task builds and run from my temp directory the if for any reason (restart mainly) tmpDir is flushed and the compiled build is destroyed which a bit annoying considering it isn't the quickest thing to build.

Should we just build and run from project dir? or is there a better way to make this make this a bit less painful?

**Comment by paulcbetts** [comment]
On Linux this kind of sucks because many distros mount `/tmp` as a tmpfs, you can disable this feature afaik

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom-archive/electron-starter), this package is no longer maintained and is deprecated. We recommend that people use [electron-prebuilt](https://github.com/mafintosh/electron-prebuilt) and [electron-packager](https://github.com/maxogden/electron-packager) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
