### ISSUE TITLE
Where can I find / how can I build an OSX binary

### ISSUE THREAD

**Issue by almathie** [atom-archive/electron-starter#84]
I have an app that successfully works when being executed by script/run
I'd like to distribute the app in a regular OSX .app

Where can I find / how can I build this self-contained executable.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom-archive/electron-starter), this package is no longer maintained and is deprecated. We recommend that people use [electron-prebuilt](https://github.com/mafintosh/electron-prebuilt) and [electron-packager](https://github.com/maxogden/electron-packager) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
