### ISSUE TITLE
Code Changes Have No Effect

### ISSUE THREAD

**Issue by fiedl** [atom-archive/electron-starter#85]
Thanks for this starter project. As I'm new to electron, I'm struggling with a very basic thing:

**Code Changes have no effect on the application until I run `script/build` again.**
### Steps to reproduce
1. Clone the repository to a local path.
2. Following the [README](https://github.com/atom/electron-starter/blob/master/README.md), change `package.json`.
3. run `script/bootstrap`
4. run `script/build`
5. run `script/run --dev`
6. Change some code, for example in `src/renderer/main.coffee` or `static/index.html`.
7. Reload the application, either using `⌘+R`, or running `script/run --dev` again.
### Expected Behavior

From the [README](https://github.com/atom/electron-starter/blob/master/README.md) I would expect code changes to take effect immediately, i.e. after `⌘+R`.

> `script/build` - Run this whenever you change package.json or change early startup code
> `script/run` - Run the app. Use this for running the app in developer mode
### Observed Behavior

Code changes, for example in `src/renderer/main.coffee` or `static/index.html`, have no effect when refreshing using `⌘+R` or rerunning the application by `script/run --dev`. 

I have to rebuild using `script/build`, which takes quite a long time (about 30 minutes).
### Environment

Mac OS X Yosemite 10.10.3
Node: v0.10.38
npm: v1.4.28

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom-archive/electron-starter), this package is no longer maintained and is deprecated. We recommend that people use [electron-prebuilt](https://github.com/mafintosh/electron-prebuilt) and [electron-packager](https://github.com/maxogden/electron-packager) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
