### ISSUE TITLE
How to open two browser windows using separate context?

### ISSUE THREAD

**Issue by gajus** [atom-archive/electron-starter#89]
> Please close. This was intended for https://github.com/atom/electron.

I would like to open two windows that do not share session between them, e.g. I expect that using the following code opening github.com each window would be assigned different session IDs.

I would like to have some method to communicate between two windows.

``` js
var app = require('app'),
    BrowserWindow = require('browser-window');

app.on('window-all-closed', function () {
    if (process.platform !== 'darwin') {
        app.quit();
    }
});

app.on('ready', function () {
    var mainWindow;

    mainWindow = new BrowserWindow({width: 800, height: 600, frame: false, x: 100, y: 100, resizable: false});
    mainWindow.loadUrl('https://github.com/login');

    mainWindow.on('closed', function () {
        mainWindow = null;
    });
});

app.on('ready', function () {
    var mainWindow;

    mainWindow = new BrowserWindow({width: 800, height: 600, frame: false, x: 200, y: 200, resizable: false});
    mainWindow.loadUrl('https://github.com/login');

    mainWindow.on('closed', function () {
        mainWindow = null;
    });
});
```

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom-archive/electron-starter), this package is no longer maintained and is deprecated. We recommend that people use [electron-prebuilt](https://github.com/mafintosh/electron-prebuilt) and [electron-packager](https://github.com/maxogden/electron-packager) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
