### ISSUE TITLE
How to use coffeescript and less in static folder?

### ISSUE THREAD

**Issue by imdreamrunner** [atom-archive/electron-starter#92]
I found in Gruntfile.coffee, the electron-starter is actually compiling coffee and less code in static folder.
But I couldn't use it in the browser page, which gives 404 not found error.

Thanks in advance.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom-archive/electron-starter), this package is no longer maintained and is deprecated. We recommend that people use [electron-prebuilt](https://github.com/mafintosh/electron-prebuilt) and [electron-packager](https://github.com/maxogden/electron-packager) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
